name: Update Preview Release

on:
  workflow_dispatch: -- manuall trigger
  
  push:
    branches:
      - master

  create: -- tag added
    branches:
      - master
      
  delete: -- tag removed
    branches:
      - master

jobs:
  create:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: "recursive"

      - name: List changes
        shell: cmd
        run: |
          rem Find last tag
          for /F %%i in ('git describe --tags --abbrev^=0') do set tag=%%i
          echo Tag: %tag%
          if %tag%=="" (echo ::error::Last tag not found!& exit 1)
          rem Check for commits since the tag
          for /F %%i in ('git rev-list %tag%..HEAD') do set commits=%%i
          if %commits%=="" (echo No commits& exit 0)
          echo Commits: %commits%
          echo ## Changes since %tag%:
          git show -s --format="* %%s" %tag%..HEAD
          echo Done
